global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'todo-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8081']
        labels:
          application: 'todo-app'
          environment: 'production'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']